### PR TITLE
Cm 10.1

### PR DESCRIPTION
**Pull request by metaiiica**
fix Errors in P990 Repos

### CODE REVIEW

**Comment by OldDroid** [comment]
you didnt changed anything ...

**Comment by metaiiica** [comment]
This is not correct...

AndroidProducts.mk was corrupt and i had p990.mk deleted and pac_p990.mk 
added :)

Am 20.02.2013 17:31, schrieb Alexander Pohl:

**Comment by bluefa1con** [comment]
redo the commit with only the rename 
cant see any other change
- 63 additions
- 63 deletions

**Comment by szlkiev** [comment]
add you as device maintainer, your get access to vendor/pac.

```
63 additions
63 deletions
```

is because previously you copy paste not from raw text format. your AndroidProducts.mk is corrupt, but not the one in original vendor/pac

so don't merge this, just clean repo sync your vendor/pac, make your fix, clean junk, test build, then push directly

**Pull request closed without merging**
