### PR TITLE
Vanquish Support

### PR DESCRIPTION
**Pull request by Bkjolly**
We'd like to support PAc-man for Motorola.

### CODE REVIEW

**Comment by Nick0703** [comment]
Its missing dependencies.....

**Comment by Bkjolly** [comment]
Yes some issues but tested I need to commit a dependencies but you can read the thread I use a local manifest usually. http://droid-hive.com/index.php?/topic/1728-alpha-pac-man-rom-ported-by-bkjolly/

**Comment by Bkjolly** [comment]
There are a bunch of Motos on that site supported

**Comment by Bkjolly** [comment]
Uploading the Razr HD dependencies to the server now I can commit those tonight The others will be tommorow

**Comment by OldDroid** [comment]
well i want to see all things added ;-)
then i will merge ...

**Comment by szlkiev** [comment]
Bkjolly, added you as device maintainer, you have access to vendor/pac & some device tree.
Please also register to pac-man-rom.de/forum and contact admin to assign you as subforum maintainer also

**Comment by Bkjolly** [comment]
Thanks. Okay guys I am having an issue it was random on builds but no it is like it every build. The Motorola's are booting with system/etc/paranoid/properties.conf having owner and group set to root:root. Obviously I need them set to system:system does anyone have any insight?

**Comment by sudwind** [comment]
This is the problem I believe https://github.com/ParanoidAndroid-armv6/android_system_core/commit/d61c1cbb79d37db147f168ea642ea32993a4a0ab, only if you're using another android_system_core repo.

**Pull request merged**
