### PR TITLE
pac: add Xperia T (mint)

### PR DESCRIPTION
**Pull request by LalitMaganti**
Repos to be forked are 
https://github.com/CyanogenMod/android_device_sony_blue-common
and
https://github.com/CyanogenMod/android_device_sony_mint

### CODE REVIEW

**Comment by n1kolaa** [comment]
Good to see more phones suported to pac project

**Comment by ExPeacer** [comment]
One question: You wanna modify this device trees? If not, you don't need fork it. You can add CM repos too to the dependencies.

**Comment by championswimmer** [comment]
@Lalit
blue-common will need forking
mint we can keep working with CM tree

# 

catch me on my website :
www.championswimmer.co.cc

**Comment by n1kolaa** [comment]
can someone give me permision to fork to pac ?
need to add sometings for arc/s

**Comment by szlkiev** [comment]
@n1kolaa, ok

**Comment by n1kolaa** [comment]
tnx

**Pull request merged**
