### PR TITLE
Update nightly.xml

### PR DESCRIPTION
**Pull request by danparidae**

### CODE REVIEW

**Comment by Nick0703** [comment]
Please submit your patch via Gerrit. We don't accept Pull Request.

**Comment by danparidae** [comment]
ok, sorry. didn't know. any guide?

**Comment by Nick0703** [comment]
https://github.com/PAC-man/android_vendor_pac/blob/pac-5.0/docs/HowToUseGerrit.md

**Comment by danparidae** [comment]
thanks!

**Pull request closed without merging**
