### PR TITLE
Switch vigor to new CM device sources

### PR DESCRIPTION
**Pull request by shrike1978**

### CODE REVIEW

**Comment by Papa-Smurf151** [comment]
Please push via gerrit.  We no longer push directly to pac github directly

**Comment by blindndumb** [comment]
Push via gerrit
Here's how to :
code.nwwn.com:8080/#/c/51/6/README.md

**Comment by ghost** [comment]
@blindndumb 
It got Merged : Here's How to - https://github.com/PAC-man/android

**Comment by championswimmer** [comment]
remove push rights on github for everyone @szlkiev 
keep it for 2-3 super-admin sort of members (you might need them when jb-mr2 comes for rebase and force pushes)

heck even people like me are having push rights who have contributed maybe only 2-3 commits directly to PAC-man ever :P
lol

**Comment by szlkiev** [comment]
@champ, but you're my mentor as always :)

**Pull request closed without merging**
