### PR TITLE
Add Nexus Q (steelhead) support

### PR DESCRIPTION
**Pull request by manelscout4life**
Change-Id: I89a03cd33e22e69fc7700ba3f59f6bed3da0935f

### CODE REVIEW

**Comment by Papa-Smurf151** [comment]
Please submit via gerrit.  Please include all support files found at
Www.pac-rom.com/BecomeMaintainer

**Comment by Bkjolly** [comment]
Wow Nexus Q support. Really?

**Comment by manelscout4life** [comment]
Bkjolly, eh why not...

**Comment by Bkjolly** [comment]
That's what I'm saying push it to gerrit man this is cool.

**Comment by manelscout4life** [comment]
Done.

**Pull request closed without merging**
