### PR TITLE
Add support for n7000 and i9300

### PR DESCRIPTION
**Pull request by beerbong**
I've already built for both devices. Tested for n7000. Will test for the i9300 tonight.
Change-Id: I79928793d3664709e59b02734929f4757bfc56f1

### CODE REVIEW

**Comment by szlkiev** [comment]
Added you as team member, welcome onboard

**Comment by Papa-Smurf151** [comment]
Hey szk can u start directing new maintainers to the forum when u add them
so we can get them set up too

**Comment by szlkiev** [comment]
OK chad, will do also next.

@beerboong, please register to pac-man-rom.de/forum
Please contact one of the admin to set you up as device sub forum maintainer

**Comment by beerbong** [comment]
Already registered and with maintainer rol. Will contact an admin later.

**Pull request merged**
