### PR TITLE
add sony yuga device

### PR DESCRIPTION
**Pull request by jeroenqui**

### CODE REVIEW

**Comment by jeroenqui** [comment]
I have tried the current dpi's with the profiles (phone, phablet and tablet) I set on the device, and those where most ideal. I will try out your suggested dpi values and see if they're ok.

Regarding the min/max values, although I agree 160 is overkill, some people would still want it :-)

**Comment by BytecodeX** [comment]
Nice work @jeroenqui. Just needs some little fixes here and there.

To all of you, I'm getting back on PAC soon, I will contribute much more than before. First of all I'll add mint (Xperia T), then I'll check other things out.

**Comment by jeroenqui** [comment]
Thanks @BytecodeX 
I already fixed some things in the latest commit.
Did you see anything else that needs fixing? Let me know!

**Comment by vertigo2012** [comment]
@BytecodeX I was going to do mint, but as CM10.1 isn't working fully I've been hanging back until its fixed, feel free to take over though as I've already got enough devices to look after lol ;)

**Comment by BytecodeX** [comment]
It can actually be used as a daily basis, just camera does not work and I'm
working on it ;) it's a blob issue
Il giorno 04/apr/2013 14:02, "vertigo2012" notifications@github.com ha
scritto:

**Comment by jeroenqui** [comment]
Sames goes for the Xperia Z too (yuga), camera is not working either, but for the rest it can be used as a daily driver (I'm using it)

**Comment by BytecodeX** [comment]
Yep. That's uh.. that's because of the incompatibility between mako 4.2.2 blobs and yuga/mint camera. I tried the ones released in march by Qualcomm for 4.2 (adreno 2xx and 3xx) and they broke display. Guess we'll have to give a shot to stock blobs as well, but there are already much much changes in kernel and device folder reflecting support for mako blobs. We're kind of in a limbo

**Pull request merged**
