### PR TITLE
Disable camera sounds part 4

### PR DESCRIPTION
**Pull request by Jaiglissechef-i9100**

### CODE REVIEW

**Comment by Papa-Smurf151** [comment]
Please submit via gerrit. We don't accept pull requests on github

**Comment by Jaiglissechef-i9100** [comment]
gerrit dont work for me, made an issue: p

**Comment by Papa-Smurf151** [comment]
Not my problem.  Our repos are synced with gerrit so we can't and won't
accept pull requests

**Comment by Jaiglissechef-i9100** [comment]
Ok np

**Pull request closed without merging**
