### PR TITLE
Add Support for Xperia ZR (dogo)

### PR DESCRIPTION
**Pull request by arnavgosain**
Sorry, I couldn't figure out how to use github so I thought of making a pull request.

Current bugs:
Camera
UI is laggy on first boot.

### CODE REVIEW

**Comment by Grarak** [comment]
Please use gerrit

**Comment by Papa-Smurf151** [comment]
That and ur using the cricket d2.mk file which is not for ur device

**Comment by arnavgosain** [comment]
I couldn't figure out how to use gerrit as I am on windows :|

**Comment by Papa-Smurf151** [comment]
Hit me up on hangouts

CBarlan@gmail.com

**Comment by arnavgosain** [comment]
@Papa-Smurf151: Just pinged you. Arnav Gosain here.

**Comment by Goldflame09** [comment]
should this be closed now?

**Comment by Papa-Smurf151** [comment]
Lol yes it shouldve been supported on gerrit

**Pull request closed without merging**
